### ISSUE TITLE
Bug in domain extraction in html rendering

### ISSUE THREAD

**Issue by ignazio1977** [co-ode-owl-plugins/ontology-browser#64]
Domain extraction causes an error for object properties:

    org.semanticweb.owlapi.model.OWLRuntimeException: Not a data property!
    at uk.ac.manchester.cs.owl.owlapi.OWLObjectPropertyImpl.asOWLDataProperty(OWLObjectPropertyImpl.java:175)
    at org.coode.html.doclet.DomainsDoclet.getAssertedElements(DomainsDoclet.java:32)
    at org.coode.html.doclet.AbstractOWLElementsDoclet.getElements(AbstractOWLElementsDoclet.java:67)
    at org.coode.html.doclet.ElementsDoclet.renderHeader(ElementsDoclet.java:57)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderAll(AbstractHTMLDoclet.java:50)
    at org.coode.html.doclet.AbstractHTMLDoclet.renderContent(AbstractHTML

**Comment by ignazio1977** [comment]
Causes https://github.com/co-ode-owl-plugins/owldoc/issues/1
